-- Create Profiles Table (Linked to Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text,
  email text,
  cpf text,
  phone text,
  address_zip text,
  address_street text,
  address_number text,
  address_complement text,
  address_district text,
  address_city text,
  address_state text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Policies for Profiles
drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile"
  on profiles for select
  using ( auth.uid() = id );

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile"
  on profiles for insert
  with check ( auth.uid() = id );

-- Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price decimal(10,2) not null,
  image text not null,
  category text not null,
  description text,
  sizes text[] default '{}',
  colors text[] default '{}',
  rating decimal(2,1) default 5.0,
  reviews integer default 0,
  is_new boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Policies for Products
drop policy if exists "Public Products are viewable by everyone" on products;
create policy "Public Products are viewable by everyone"
  on products for select
  using ( true );

drop policy if exists "Enable insert for everyone" on products;
create policy "Enable insert for everyone"
  on products for insert
  with check ( true );

drop policy if exists "Enable update for everyone" on products;
create policy "Enable update for everyone"
  on products for update
  using ( true );

drop policy if exists "Enable delete for everyone" on products;
create policy "Enable delete for everyone"
  on products for delete
  using ( true );


-- Seed Data (Check if exists to avoid duplicates)
insert into public.products (name, price, image, category, description, sizes, is_new)
select 'Vestido Floral Verão', 89.90, 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=500&auto=format&fit=crop', 'Meninas', 'Vestido leve e confortável com estampa floral exclusiva.', ARRAY['2', '4', '6', '8'], true
where not exists (select 1 from public.products where name = 'Vestido Floral Verão');

insert into public.products (name, price, image, category, description, sizes, is_new)
select 'Conjunto Aventura Dino', 79.90, 'https://images.unsplash.com/photo-1547796011-0672152a5a51?q=80&w=500&auto=format&fit=crop', 'Meninos', 'Camiseta e bermuda em algodão macio.', ARRAY['2', '4', '6'], true
where not exists (select 1 from public.products where name = 'Conjunto Aventura Dino');

insert into public.products (name, price, image, category, description, sizes, is_new)
select 'Romper Jardim Secreto', 65.00, 'https://images.unsplash.com/photo-1522771930-78848d9293e8?q=80&w=500&auto=format&fit=crop', 'Bebês', 'Romper delicado com babados.', ARRAY['P', 'M', 'G'], false
where not exists (select 1 from public.products where name = 'Romper Jardim Secreto');

-- Create Store Settings Table (Singleton)
create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text default 'DeLu Kids',
  free_shipping_threshold decimal(10,2) default 299.00,
  contact_email text,
  contact_phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on store_settings
alter table public.store_settings enable row level security;

-- Policies for Store Settings
drop policy if exists "Public Store Settings are viewable by everyone" on store_settings;
create policy "Public Store Settings are viewable by everyone"
  on store_settings for select
  using ( true );

drop policy if exists "Enable insert for everyone" on store_settings;
create policy "Enable insert for everyone"
  on store_settings for insert
  with check ( true );

drop policy if exists "Enable update for everyone" on store_settings;
create policy "Enable update for everyone"
  on store_settings for update
  using ( true );

-- Seed Default Settings
insert into public.store_settings (store_name, free_shipping_threshold)
select 'DeLu Kids', 299.00
where not exists (select 1 from public.store_settings limit 1);

-- Create Orders Table
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id), -- Linked to User
  customer_name text not null,
  customer_phone text,
  total decimal(10,2) not null,
  status text default 'Pendente',
  payment_method text not null,
  address text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on orders
alter table public.orders enable row level security;

-- Policies for Orders
drop policy if exists "Users can view own orders" on orders;
create policy "Users can view own orders"
  on orders for select
  using ( auth.uid() = user_id );

-- Add Payment and Shipping Columns to Store Settings
alter table public.store_settings add column if not exists pix_key text;
alter table public.store_settings add column if not exists pix_owner_name text;
alter table public.store_settings add column if not exists pix_owner_city text;
alter table public.store_settings add column if not exists fixed_shipping_price numeric default 15.00;


drop policy if exists "Users can insert own orders" on orders;
create policy "Users can insert own orders"
  on orders for insert
  with check ( auth.uid() = user_id );
  
drop policy if exists "Enable update for everyone" on orders;
create policy "Enable update for everyone"
  on orders for update
  using ( true );

-- Create Order Items Table
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  product_name text not null,
  quantity integer not null,
  size text,
  price decimal(10,2) not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on order_items
alter table public.order_items enable row level security;

-- Policies for Order Items
drop policy if exists "Users can view own order items" on order_items;
create policy "Users can view own order items"
  on order_items for select
  using ( exists ( select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid() ) );

drop policy if exists "Users can insert own order items" on order_items;
create policy "Users can insert own order items"
  on order_items for insert
  with check ( exists ( select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid() ) );

